version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    working_directory: ~/Mealplanr/api
    steps:
      - checkout:
          path: ~/Mealplanr
      - run:
          name: Install dependencies
          command: |
            yarn install

workflows:
  build_test:
    jobs:
      - run_tests
