version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16
    working_directory: ~/Mealplanr/api
    steps:
      - name: elevate #https://github.com/actions/checkout/issues/211
        run: |
          echo ${{secrets.DEPLOY_PASSWORD}} | sudo -S chown -R $USER:$USER $GITHUB_WORKSPACE
      - checkout:
          path: ~/Mealplanr
      - run:
          name: Install dependencies
          command: |
            yarn install

workflows:
  build_test:
    jobs:
      - run_tests
