name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:

# ! Repo Project---------------------------------------------------------------------------------------
    - name: Assign issues to repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/BHelpful/Mealplanr/projects/1'

    - name: Assign issues to repo project in In progress column when assigned
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event == 'issue' &&
        (
          github.event.action == 'assigned'
        )
      with:
        project: 'https://github.com/BHelpful/Mealplanr/projects/1'
        column_name: 'In progress'
