name: Auto Assign repo Project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign
    steps:

# ! Repo Project---------------------------------------------------------------------------------------
    - name: Assign issues to repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' || github.event.action == 'reopened'
      with:
        project: 'https://github.com/BHelpful/Mealplanr/projects/1'
