name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:

# ! Repo Project---------------------------------------------------------------------------------------
    - name: Assign issues to repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event == 'issue' &&
        (
          github.event.action == 'opened'
        )
      with:
        project: 'https://github.com/BHelpful/Mealplanr/projects/1'

    - name: Assign pull requests repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        github.event == 'pull_request' &&
        (
          github.event.action == 'opened'
        )
      with:
        project: 'https://github.com/BHelpful/Mealplanr/projects/1'
